---
# Ansible主机清单文件
# 定义需要初始化的服务器

all:
  children:
    # 生产服务器组
    production:
      hosts:
        # 示例主机，请根据实际情况修改
        # prod-server-01:
        #   ansible_host: 192.168.1.10
        #   ansible_user: root
        # prod-server-02:
        #   ansible_host: 192.168.1.11
        #   ansible_user: root
      vars:
        # 生产环境变量
        environment_type: production
        
    # 测试服务器组  
    staging:
      hosts:
        # staging-server-01:
        #   ansible_host: 192.168.1.20
        #   ansible_user: root
      vars:
        environment_type: staging
        
    # 开发服务器组
    development:
      hosts:
        # dev-server-01:
        #   ansible_host: 192.168.1.30
        #   ansible_user: root
      vars:
        environment_type: development

  vars:
    # 全局变量
    ansible_python_interpreter: /usr/bin/python3
    # 如果使用密钥文件
    # ansible_ssh_private_key_file: ~/.ssh/id_rsa 