---
# 简化的服务器初始化 Playbook
# 运行命令: ansible-playbook -i inventory.yml server-setup.yml

- name: "服务器基础配置"
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    # 可修改的变量
    server_timezone: "Asia/Shanghai"
    # SSH公钥配置 - 请添加你的公钥内容
    ssh_public_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... your-public-key-here"
      # - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... another-key-here"
    
    # 用户配置
    admin_users:
      - name: "{{ ansible_user }}"  # 使用当前连接的用户
        groups: ["sudo"]
        shell: "/bin/bash"
    
    install_packages:
      - vim
      - curl
      - wget
      - htop
      - git
      - unzip
      - tree
      - screen
      - tmux
  
  tasks:
    # 1. 系统基础配置
    - name: "更新软件包缓存"
      apt:
        update_cache: yes
        cache_valid_time: 86400
      when: ansible_os_family == "Debian"
      tags: ['system']

    - name: "设置时区"
      timezone:
        name: "{{ server_timezone }}"
      tags: ['system']

    - name: "确保时区配置文件正确"
      file:
        src: "/usr/share/zoneinfo/{{ server_timezone }}"
        dest: "/etc/localtime"
        state: link
        force: yes
      tags: ['system']

    - name: "写入时区到/etc/timezone"
      copy:
        content: "{{ server_timezone }}\n"
        dest: /etc/timezone
        mode: '0644'
      tags: ['system']

    - name: "设置主机名到/etc/hostname"
      copy:
        content: "{{ inventory_hostname }}\n"
        dest: /etc/hostname
        mode: '0644'
      tags: ['system']

    - name: "设置运行时主机名"
      hostname:
        name: "{{ inventory_hostname }}"
      tags: ['system']

    - name: "更新/etc/hosts文件"
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1\t{{ inventory_hostname }}"
        backup: yes
      tags: ['system']

    - name: "确保localhost条目存在"
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: "127.0.0.1\tlocalhost"
        backup: yes
      tags: ['system']

    # 2. 安装基础软件
    - name: "安装基础工具"
      package:
        name: "{{ install_packages }}"
        state: present
      tags: ['packages']

    - name: "安装Python包"
      package:
        name:
          - python3
          - python3-pip
        state: present
      tags: ['packages']

    # 3. 用户和SSH密钥管理
    - name: "确保管理员用户存在"
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: "{{ item.shell }}"
        append: yes
        create_home: yes
      loop: "{{ admin_users }}"
      tags: ['users', 'security']

    - name: "为管理员用户创建.ssh目录"
      file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0700'
      loop: "{{ admin_users }}"
      when: item.name != 'root'
      tags: ['users', 'security']

    - name: "为root用户创建.ssh目录"
      file:
        path: "/root/.ssh"
        state: directory
        owner: root
        group: root
        mode: '0700'
      when: "'root' in admin_users | map(attribute='name') | list"
      tags: ['users', 'security']

    - name: "添加SSH公钥到管理员用户"
      authorized_key:
        user: "{{ item.0.name }}"
        key: "{{ item.1 }}"
        state: present
        exclusive: no
      loop: "{{ admin_users | product(ssh_public_keys) | list }}"
      when: ssh_public_keys is defined and ssh_public_keys | length > 0
      tags: ['users', 'security']

    - name: "验证SSH公钥是否已正确配置"
      command: "ls -la /home/{{ ansible_user }}/.ssh/authorized_keys"
      register: ssh_key_check
      failed_when: false
      changed_when: false
      when: ansible_user != 'root'
      tags: ['security', 'verify']

    - name: "验证root用户SSH公钥配置"
      command: "ls -la /root/.ssh/authorized_keys"
      register: root_ssh_key_check
      failed_when: false
      changed_when: false
      when: ansible_user == 'root'
      tags: ['security', 'verify']

    - name: "显示SSH密钥配置状态"
      debug:
        msg: |
          🔑 SSH密钥配置状态:
          {% if ansible_user != 'root' and ssh_key_check.rc == 0 %}
          ✅ 用户 {{ ansible_user }} 的公钥已配置
          {% elif ansible_user == 'root' and root_ssh_key_check.rc == 0 %}
          ✅ root用户的公钥已配置
          {% else %}
          ⚠️  警告：未检测到SSH公钥配置！
          {% endif %}
          
          📝 请确认以下公钥已正确添加：
          {% for key in ssh_public_keys %}
          - {{ key[:50] }}...
          {% endfor %}
      when: ssh_public_keys is defined
      tags: ['security', 'verify']

    # 4. 系统优化配置
    - name: "配置系统limits"
      copy:
        dest: /etc/security/limits.d/99-custom.conf
        content: |
          * soft nofile 65536
          * hard nofile 65536
          * soft nproc 32768
          * hard nproc 32768
        backup: yes
      tags: ['optimize']

    - name: "配置基础网络参数"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'net.core.somaxconn', value: '65535' }
        - { name: 'net.ipv4.tcp_fin_timeout', value: '10' }
        - { name: 'net.ipv4.tcp_keepalive_time', value: '1200' }
      ignore_errors: yes
      tags: ['optimize']

    # 5. SSH安全配置（在公钥配置完成后）
    - name: "警告：即将配置SSH安全设置"
      pause:
        prompt: |
          ⚠️  即将禁用SSH密码认证！
          
          请确认：
          1. SSH公钥已正确配置
          2. 你能够使用密钥登录
          
          按 Enter 继续，或 Ctrl+C 取消
        seconds: 10
      when: ssh_public_keys is defined and ssh_public_keys | length > 0
      tags: ['security']

    - name: "配置SSH安全设置"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
      loop:
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin prohibit-password' }
        - { regexp: '^#?AuthorizedKeysFile', line: 'AuthorizedKeysFile .ssh/authorized_keys' }
      notify: restart ssh
      when: ssh_public_keys is defined and ssh_public_keys | length > 0
      tags: ['security']

    - name: "跳过SSH安全配置（未配置公钥）"
      debug:
        msg: |
          ⚠️  跳过SSH安全配置！
          
          原因：未配置SSH公钥
          
          要启用SSH安全配置，请：
          1. 在vars中添加你的SSH公钥到 ssh_public_keys
          2. 重新运行playbook：ansible-playbook server-setup.yml --tags security
      when: ssh_public_keys is not defined or ssh_public_keys | length == 0
      tags: ['security']

    # 6. 创建有用的别名
    - name: "创建系统别名"
      copy:
        dest: /etc/profile.d/aliases.sh
        content: |
          alias ll='ls -alF'
          alias la='ls -A'
          alias l='ls -CF'
          alias ..='cd ..'
          alias df='df -h'
          alias free='free -h'
          alias top='htop'
        mode: '0644'
      tags: ['config']

    # 7. 验证配置
    - name: "验证时区设置"
      command: timedatectl show --property=Timezone --value
      register: current_timezone
      changed_when: false
      tags: ['system', 'verify']

    - name: "验证主机名设置"
      command: hostname
      register: current_hostname
      changed_when: false
      tags: ['system', 'verify']

    # 8. 显示完成信息
    - name: "显示配置完成信息"
      debug:
        msg: |
          ✅ 服务器配置完成！
          📍 主机: {{ inventory_hostname }} (当前: {{ current_hostname.stdout }})
          🖥️  系统: {{ ansible_distribution }} {{ ansible_distribution_version }}
          🔧 已安装工具: {{ install_packages | join(', ') }}
          🕐 时区: {{ server_timezone }} (当前: {{ current_timezone.stdout }})
          👤 管理员用户: {{ admin_users | map(attribute='name') | join(', ') }}
          
          {% if ssh_public_keys is defined and ssh_public_keys | length > 0 %}
          🔐 SSH安全: 已启用密钥认证，已禁用密码登录
          {% else %}
          ⚠️  SSH安全: 未配置（仍允许密码登录）
          {% endif %}
          
          💡 下次登录请使用: ssh -i ~/.ssh/your_private_key {{ ansible_user }}@{{ ansible_host }}
      tags: ['info']

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted 